#!/usr/bin/sh

pushd ../build/pulcher-binaries
git checkout win64
cp -r ../install-release-win64/bin/plugins/ .
cp ../install-release-win64/bin/imgui.ini .
cp ../install-release-win64/bin/pulcher-client.exe .
cp -r ../install-release-win64/bin/*.dll .

git add plugins/
git add imgui.ini
git add pulcher-client.exe
git add *.dll

git commit -m "update pulcher binaries"
git push

popd
