#!/usr/bin/sh

commitM="$*"
pushd ../build/pulcher-binaries
git stash
git checkout linux
cp -r ../install-release-linux/bin/plugins/ .
cp ../install-release-linux/bin/imgui.ini .
cp ../install-release-linux/bin/pulcher-client .
cp -r ../install-release-linux/lib/ .

git add plugins/
git add imgui.ini
git add pulcher-client
git add lib/

git commit -m "${commitM}"
git push
popd

pushd ../build/pulcher-binaries
git stash
git checkout win64
cp -r ../install-release-win64/bin/plugins/ .
cp ../install-release-win64/bin/imgui.ini .
cp ../install-release-win64/bin/pulcher-client.exe .
cp -r ../install-release-win64/bin/*.dll .

git add plugins/
git add imgui.ini
git add pulcher-client.exe
git add *.dll

# check for assets update
cd assets
git pull
cd ..
git status
if [[ `git status --porcelain` ]]; then
  echo " --- updating git assets ---"
  git add assets
fi

git commit -m "${commitM}"
git push
popd
